// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwavciytqnzwoqqlcvta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3YXZjaXl0cW56d29xcWxjdnRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjY1NDAsImV4cCI6MjA2NjQ0MjU0MH0.GN87sWKOT9icXMYkJe466I6Es4xgNngzkdB9Q_jBUPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);